### ISSUE TITLE
Make ASP.NET Core endpoint return each line as it becomes available?

### ISSUE THREAD

**Issue by Regenhardt** [cainy-a/JsonLines.NET#1]
How about an attribute you can add to an endpoint when the endpoint returns an IEnumerable or IAsyncEnumerable, so the attribute will take the enumerable being returned, enumerates it, and serializes each object into the response http stream as soon as it becomes available? This could speed up the usage in the frontend, and also enable things like a progress bar that shows the actual progress.

I imagine something like this:

```
[Jsonlines]
public IAsyncEnumerable<FlightPlan> CompareFlights(TravelData input)
{...}
```

Then it would take the IAsyncEnumerable (maybe from an EFcore call), awaits each object, then serializes that, writes it into the response stream, and then awaits the next object.

**Comment by yellowsink** [comment]
Great idea! Im not sure an attribute is how to approach this though, surely just a method (extension perhaps) that takes the async enumerable and returns another?

**Comment by Regenhardt** [comment]
The idea was to return one object after another, so the receiver gets the chance to process after after another.

I assumed the asp.net core runtime would completely enumerate the IEnumerable before returning the whole list, but now that I think about it I realise, I don't actually know that. 

Either way, returning an IEnumerable will always return the objects wrapped in a list, not as json lines. So we could build a method to enumerate and serialize the objects into a string, but even then I'm not sure we can kinda...start sending it to the caller before being done processing the whole thing. 

So that's why my only idea about how to make sure each finished object is immediately sent to the caller before processing the next one is to touch the actual response stream, which AFAIK only works with an attribute on a controller method.

**Comment by yellowsink** [comment]
Is it maybe more sensible to make a `Stream` implementation that lazily serializes an IEnumerable<T> to utf8 bytes?

That way your IEnumerable input can be lazy.

**Comment by yellowsink** [comment]
But even then IEnumerables are lazy and with some internal reworking could be easily done I think

**Comment by Regenhardt** [comment]
Would the controller method return the stream then, so the caller can read from the stream? Can we create a stream, return it from the controller method, and _then_ write to it lazily?

**Comment by yellowsink** [comment]
Should be able to.

**Comment by yellowsink** [comment]
Surely the controller is just called via a HTTP request though, right?

I'm not sure what the "caller" is in this case.

**Comment by Regenhardt** [comment]
Yes, caller means whatever is doing an HTTP request here.

**Comment by Regenhardt** [comment]
Never actually returned a stream from a controller method, so I'm not entirely sure how to format that. Would we have to write the headers ourselves?

**Comment by yellowsink** [comment]
~~Assuming you're using an MVC, you do `return File(stream, mimeType)`~~

~~In this case you'd *probably* use `application/json` as the mime type~~

You write to `Response.OutputStream` and return `new EmptyResult()`.
